begin;

alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists role text not null default 'student';
alter table public.profiles add column if not exists status text not null default 'pending';
alter table public.profiles add column if not exists data_expiracao timestamptz;
alter table public.profiles add column if not exists email_verified boolean default false;
alter table public.profiles add column if not exists permissions jsonb not null default '{
  "friends": true, "readclub": true, "board": true, "quiz": true, "biacompare": true,
  "conversation": true, "tradutor": true, "youtube": true, "practice": true, "stories": true
}'::jsonb;
alter table public.profiles add column if not exists ip_country text;
alter table public.profiles add column if not exists ip_region text;
alter table public.profiles add column if not exists ip_city text;
alter table public.profiles add column if not exists cupom_usado text;
alter table public.profiles add column if not exists photo_url text;
alter table public.profiles add column if not exists location_consent boolean not null default false;
alter table public.profiles add column if not exists auth_user_id text;
create unique index if not exists idx_profiles_auth_user_id on public.profiles (auth_user_id) where auth_user_id is not null;
alter table public.bia_subscription_profiles add column if not exists user_id text;

create table if not exists public.bia_shared_content (
  content_key text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.bia_student_progress (
  user_id text primary key,
  sessions jsonb not null default '[]'::jsonb,
  glossary jsonb not null default '{}'::jsonb,
  learned_words jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.bia_ceo_friend_messages (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  receiver_id text not null,
  body text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '5 days')
);
create table if not exists public.bia_trial_coupons (
  id text primary key,
  code text not null unique,
  days integer not null default 2,
  is_used boolean not null default false,
  used_by_email text,
  used_at timestamptz,
  expires_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);
create table if not exists public.bia_payment_intents (
  payment_id text primary key,
  user_id text,
  email text not null,
  amount_cents integer not null check (amount_cents > 0),
  status text not null default 'pending' check (status in ('pending', 'active')),
  provider_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_bia_payment_intents_email on public.bia_payment_intents (email);
alter table public.bia_payment_intents enable row level security;
alter table public.brazilian_friends_users add column if not exists photo_url text;
alter table public.brazilian_friends_users add column if not exists status_message text;
alter table public.profiles enable row level security;
alter table public.bia_subscription_profiles enable row level security;
alter table public.stories enable row level security;
alter table public.bia_shared_content enable row level security;
alter table public.bia_student_progress enable row level security;
alter table public.bia_ceo_friend_messages enable row level security;
alter table public.bia_trial_coupons enable row level security;
alter table public.brazilian_friends_users enable row level security;
alter table public.brazilian_friends_messages enable row level security;
create or replace function public.cleanup_expired_brazilian_friend_messages_count()
returns integer
language sql
security definer
set search_path = public
as $$
  with deleted as (
    delete from public.brazilian_friends_messages
    where expires_at is not null and expires_at <= now()
    returning 1
  )
  select count(*)::integer from deleted;
$$;
revoke all on function public.cleanup_expired_brazilian_friend_messages_count() from public;
grant execute on function public.cleanup_expired_brazilian_friend_messages_count() to anon, authenticated;

drop policy if exists "profiles_all_access" on public.profiles;
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated
using (
  auth_user_id = auth.uid()::text
);

drop policy if exists "subscription_all_access" on public.bia_subscription_profiles;
drop policy if exists "Read subscription status" on public.bia_subscription_profiles;
drop policy if exists "subscription_select_own" on public.bia_subscription_profiles;
create policy "subscription_select_own" on public.bia_subscription_profiles
for select to authenticated
using (
  user_id = auth.uid()::text
);

drop policy if exists "payment_intents_select_own" on public.bia_payment_intents;
create policy "payment_intents_select_own" on public.bia_payment_intents
for select to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "stories_all_access" on public.stories;
drop policy if exists "stories_public_read_approved" on public.stories;
create policy "stories_public_read_approved" on public.stories
for select to anon, authenticated using (status in ('approved', 'featured'));
drop policy if exists "stories_insert_own_pending" on public.stories;
create policy "stories_insert_own_pending" on public.stories
for insert to authenticated with check (student_id = auth.uid()::text and status = 'pending');
drop policy if exists "stories_update_own_pending" on public.stories;
create policy "stories_update_own_pending" on public.stories
for update to authenticated using (student_id = auth.uid()::text and status = 'pending')
with check (student_id = auth.uid()::text and status = 'pending');
drop policy if exists "stories_delete_own_pending" on public.stories;
create policy "stories_delete_own_pending" on public.stories
for delete to authenticated using (student_id = auth.uid()::text and status = 'pending');

drop policy if exists "shared_content_all_access" on public.bia_shared_content;
drop policy if exists "shared_content_public_read" on public.bia_shared_content;

drop policy if exists "student_progress_all_access" on public.bia_student_progress;
drop policy if exists "student_progress_own" on public.bia_student_progress;
create policy "student_progress_own" on public.bia_student_progress
for all to authenticated using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);

drop policy if exists "ceo_friend_messages_all_access" on public.bia_ceo_friend_messages;
drop policy if exists "ceo_friend_messages_participant_read" on public.bia_ceo_friend_messages;
create policy "ceo_friend_messages_participant_read" on public.bia_ceo_friend_messages
for select to authenticated using (sender_id = auth.uid()::text or receiver_id = auth.uid()::text);
drop policy if exists "ceo_friend_messages_sender_insert" on public.bia_ceo_friend_messages;
create policy "ceo_friend_messages_sender_insert" on public.bia_ceo_friend_messages
for insert to authenticated with check (sender_id = auth.uid()::text);
drop policy if exists "ceo_friend_messages_sender_delete" on public.bia_ceo_friend_messages;
create policy "ceo_friend_messages_sender_delete" on public.bia_ceo_friend_messages
for delete to authenticated using (sender_id = auth.uid()::text);

drop policy if exists "trial_coupons_all_access" on public.bia_trial_coupons;
drop policy if exists "trial_coupons_public_read" on public.bia_trial_coupons;
create policy "trial_coupons_public_read" on public.bia_trial_coupons
for select to anon, authenticated using (false);

update public.brazilian_friends_users set ip_region = null, ip_country = null
where ip_region is not null or ip_country is not null;
drop policy if exists "Friends can read profiles" on public.brazilian_friends_users;
drop policy if exists "Users can create their own profile" on public.brazilian_friends_users;
drop policy if exists "Users can update their own profile" on public.brazilian_friends_users;
drop policy if exists "brazilian_friends_users_all_access" on public.brazilian_friends_users;
drop policy if exists "friends_profiles_authenticated_read" on public.brazilian_friends_users;
create policy "friends_profiles_authenticated_read" on public.brazilian_friends_users
for select to authenticated using (true);
drop policy if exists "friends_profile_insert_own" on public.brazilian_friends_users;
create policy "friends_profile_insert_own" on public.brazilian_friends_users
for insert to authenticated with check (id = auth.uid()::text);
drop policy if exists "friends_profile_update_own" on public.brazilian_friends_users;
create policy "friends_profile_update_own" on public.brazilian_friends_users
for update to authenticated using (id = auth.uid()::text) with check (id = auth.uid()::text);
drop policy if exists "friends_profile_delete_own" on public.brazilian_friends_users;
create policy "friends_profile_delete_own" on public.brazilian_friends_users
for delete to authenticated using (id = auth.uid()::text);

drop policy if exists "Participants can read messages" on public.brazilian_friends_messages;
drop policy if exists "Users can send as themselves" on public.brazilian_friends_messages;
drop policy if exists "brazilian_friends_messages_all_access" on public.brazilian_friends_messages;
drop policy if exists "friends_messages_participant_read" on public.brazilian_friends_messages;
create policy "friends_messages_participant_read" on public.brazilian_friends_messages
for select to authenticated
using (sender_id = auth.uid()::text or receiver_id = auth.uid()::text or receiver_id is null);
drop policy if exists "friends_messages_sender_insert" on public.brazilian_friends_messages;
create policy "friends_messages_sender_insert" on public.brazilian_friends_messages
for insert to authenticated with check (sender_id = auth.uid()::text);
drop policy if exists "friends_messages_sender_update" on public.brazilian_friends_messages;
create policy "friends_messages_sender_update" on public.brazilian_friends_messages
for update to authenticated using (sender_id = auth.uid()::text) with check (sender_id = auth.uid()::text);
drop policy if exists "friends_messages_sender_delete" on public.brazilian_friends_messages;
create policy "friends_messages_sender_delete" on public.brazilian_friends_messages
for delete to authenticated using (sender_id = auth.uid()::text);

revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
revoke all on public.bia_subscription_profiles from anon, authenticated;
grant select on public.bia_subscription_profiles to authenticated;
revoke all on public.bia_payment_intents from anon, authenticated;
grant select on public.bia_payment_intents to authenticated;
grant all on public.bia_payment_intents to service_role;
revoke all on public.stories from anon, authenticated;
grant select on public.stories to anon, authenticated;
grant insert, update, delete on public.stories to authenticated;
revoke all on public.bia_shared_content from anon, authenticated;
revoke all on public.bia_student_progress, public.bia_ceo_friend_messages from anon, authenticated;
grant select, insert, update, delete on public.bia_student_progress, public.bia_ceo_friend_messages to authenticated;
revoke all on public.bia_trial_coupons from anon, authenticated;
revoke all on public.brazilian_friends_users, public.brazilian_friends_messages from anon, authenticated;
grant select (id, full_name, photo_url, status_message, updated_at)
  on public.brazilian_friends_users to authenticated;
grant insert (id, email, full_name, photo_url, status_message),
  update (email, full_name, photo_url, status_message, updated_at)
  on public.brazilian_friends_users to authenticated;
grant select, insert, update, delete on public.brazilian_friends_messages to authenticated;

create or replace function public.register_google_profile(
  p_id text,
  p_email text,
  p_full_name text,
  p_photo_url text,
  p_location_consent boolean,
  p_ip_country text,
  p_ip_region text,
  p_ip_city text
)
returns setof public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  saved_profile public.profiles;
  clean_email text := lower(trim(p_email));
begin
  if coalesce(trim(p_id), '') = '' or clean_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Invalid Google profile identity';
  end if;

  select * into saved_profile
  from public.profiles
  where lower(email) = clean_email or auth_user_id = p_id
  order by case when lower(email) = clean_email then 0 else 1 end
  limit 1
  for update;

  if found then
    update public.profiles
    set email = clean_email,
      auth_user_id = p_id,
        full_name = coalesce(nullif(trim(p_full_name), ''), full_name),
        photo_url = coalesce(nullif(trim(p_photo_url), ''), photo_url),
        location_consent = location_consent or coalesce(p_location_consent, false),
        ip_country = case when p_location_consent then nullif(trim(p_ip_country), '') else ip_country end,
        ip_region = case when p_location_consent then nullif(trim(p_ip_region), '') else ip_region end,
        ip_city = case when p_location_consent then nullif(trim(p_ip_city), '') else ip_city end,
        updated_at = now()
    where id = saved_profile.id
    returning * into saved_profile;
  else
    insert into public.profiles (
      id, auth_user_id, email, full_name, photo_url, role, status, email_verified,
      location_consent, ip_country, ip_region, ip_city, created_at, updated_at
    ) values (
      p_id, p_id, clean_email, coalesce(nullif(trim(p_full_name), ''), split_part(clean_email, '@', 1)),
      nullif(trim(p_photo_url), ''), 'student', 'pending', true,
      coalesce(p_location_consent, false),
      case when p_location_consent then nullif(trim(p_ip_country), '') end,
      case when p_location_consent then nullif(trim(p_ip_region), '') end,
      case when p_location_consent then nullif(trim(p_ip_city), '') end,
      now(), now()
    ) returning * into saved_profile;
  end if;

  insert into public.bia_subscription_profiles (email, user_id, status, subscription_expires_at, updated_at)
  values (
    clean_email,
    p_id,
    case when saved_profile.status = 'active' and saved_profile.data_expiracao > now() then 'active' else 'pending' end,
    case when saved_profile.status = 'active' and saved_profile.data_expiracao > now() then saved_profile.data_expiracao else null end,
    now()
  )
  on conflict (email) do update
  set user_id = excluded.user_id,
      status = case
        when bia_subscription_profiles.status = 'active'
          and bia_subscription_profiles.subscription_expires_at > now() then 'active'
        else excluded.status
      end,
      subscription_expires_at = case
        when bia_subscription_profiles.status = 'active'
          and bia_subscription_profiles.subscription_expires_at > now() then bia_subscription_profiles.subscription_expires_at
        else excluded.subscription_expires_at
      end,
      updated_at = now();

  return next saved_profile;
end;
$$;

create or replace function public.redeem_google_trial_coupon(p_code text, p_email text, p_user_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  redeemed_coupon public.bia_trial_coupons;
  target_profile public.profiles%rowtype;
  expiration timestamptz;
begin
  select * into target_profile
  from public.profiles
  where lower(email) = lower(trim(p_email))
    and auth_user_id = p_user_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'profile_not_found');
  end if;

  if nullif(trim(target_profile.cupom_usado), '') is not null then
    return jsonb_build_object('ok', false, 'reason', 'trial_already_used');
  end if;

  update public.bia_trial_coupons
  set is_used = true,
      used_by_email = lower(trim(p_email)),
      used_at = now()
  where upper(code) = upper(trim(p_code))
    and is_used = false
    and (expires_at is null or expires_at > now())
  returning * into redeemed_coupon;

  if redeemed_coupon.id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_or_used');
  end if;

  select greatest(coalesce(subscription_expires_at, now()), now())
  into expiration
  from public.bia_subscription_profiles
  where lower(email) = lower(trim(p_email))
  for update;

  expiration := expiration + interval '2 days';

  update public.profiles
  set status = 'active', data_expiracao = expiration,
      cupom_usado = redeemed_coupon.code, updated_at = now()
  where lower(email) = lower(trim(p_email));

  insert into public.bia_subscription_profiles (email, user_id, status, subscription_expires_at, updated_at)
  values (lower(trim(p_email)), p_user_id, 'active', expiration, now())
  on conflict (email) do update
  set user_id = excluded.user_id, status = 'active', subscription_expires_at = excluded.subscription_expires_at, updated_at = now();

  return jsonb_build_object('ok', true, 'coupon', jsonb_build_object('code', redeemed_coupon.code, 'days', 2), 'expires_at', expiration);
end;
$$;

create or replace function public.activate_bia_payment(p_payment_id text, p_event_id text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  intent public.bia_payment_intents;
  current_expiration timestamptz;
  next_expiration timestamptz;
begin
  select * into intent
  from public.bia_payment_intents
  where payment_id = p_payment_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'reason', 'payment_not_found');
  end if;

  if intent.status = 'active' then
    return jsonb_build_object('ok', true, 'duplicate', true);
  end if;

  select subscription_expires_at into current_expiration
  from public.bia_subscription_profiles
  where lower(email) = intent.email
  for update;

  next_expiration := greatest(coalesce(current_expiration, now()), now()) + interval '30 days';

  update public.bia_payment_intents
  set status = 'active', provider_event_id = coalesce(p_event_id, provider_event_id), updated_at = now()
  where payment_id = intent.payment_id;

    insert into public.bia_subscription_profiles (email, user_id, status, subscription_expires_at, last_payment_id, updated_at)
    values (intent.email, intent.user_id, 'active', next_expiration, intent.payment_id, now())
  on conflict (email) do update
    set user_id = coalesce(excluded.user_id, public.bia_subscription_profiles.user_id),
      status = 'active', subscription_expires_at = excluded.subscription_expires_at,
      last_payment_id = excluded.last_payment_id, updated_at = now();

  update public.profiles
  set status = 'active', data_expiracao = next_expiration, updated_at = now()
  where lower(email) = intent.email;

  return jsonb_build_object('ok', true, 'duplicate', false, 'subscription_expires_at', next_expiration);
end;
$$;

revoke all on function public.register_google_profile(text, text, text, text, boolean, text, text, text) from public, anon, authenticated;
revoke all on function public.redeem_google_trial_coupon(text, text, text) from public, anon, authenticated;
revoke all on function public.activate_bia_payment(text, text) from public, anon, authenticated;
grant execute on function public.register_google_profile(text, text, text, text, boolean, text, text, text) to service_role;
grant execute on function public.redeem_google_trial_coupon(text, text, text) to service_role;
grant execute on function public.activate_bia_payment(text, text) to service_role;

drop function if exists public.redeem_trial_coupon(text, text);
revoke all on function public.check_trial_coupon(text) from public, anon, authenticated;
grant execute on function public.check_trial_coupon(text) to service_role;

commit;