-- Brazilian in Action production schema
-- Import this file in Supabase SQL Editor.

create table if not exists profiles (
  id text primary key,
  auth_user_id text,
  email text not null unique,
  full_name text,
  photo_url text,
  location_consent boolean not null default false,
  role text not null default 'student' check (role in ('student', 'admin')),
  status text not null default 'pending' check (status in ('pending', 'active', 'expired', 'trial')),
  data_expiracao timestamptz,
  permissions jsonb not null default '{
    "friends": true,
    "readclub": true,
    "board": true,
    "quiz": true,
    "biacompare": true,
    "conversation": true,
    "tradutor": true,
    "youtube": true,
    "practice": true,
    "stories": true
  }'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table profiles add column if not exists full_name text;
alter table profiles add column if not exists auth_user_id text;
alter table profiles add column if not exists photo_url text;
alter table profiles add column if not exists location_consent boolean not null default false;
alter table profiles add column if not exists role text not null default 'student';
alter table profiles add column if not exists status text not null default 'pending';
alter table profiles add column if not exists data_expiracao timestamptz;
alter table profiles add column if not exists permissions jsonb not null default '{
  "friends": true,
  "readclub": true,
  "board": true,
  "quiz": true,
  "biacompare": true,
  "conversation": true,
  "tradutor": true,
  "youtube": true,
  "practice": true,
  "stories": true
}'::jsonb;
alter table profiles add column if not exists email_verified boolean default false;
alter table profiles add column if not exists ip_country text;
alter table profiles add column if not exists ip_region text;
alter table profiles add column if not exists ip_city text;
alter table profiles add column if not exists cupom_usado text;
alter table profiles add column if not exists created_at timestamptz not null default now();
alter table profiles add column if not exists updated_at timestamptz not null default now();

-- ensure any legacy table keeps the intended constraints safely
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'profiles_role_check'
  ) then
    alter table profiles add constraint profiles_role_check check (role in ('student', 'admin'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'profiles_status_check'
  ) then
    alter table profiles add constraint profiles_status_check check (status in ('pending', 'active', 'expired', 'trial'));
  end if;
end $$;

create table if not exists stories (
  id text primary key,
  student_id text,
  student_name text,
  title text not null,
  category text not null default 'challenge',
  prompt_used text,
  video_url text,
  thumbnail_url text,
  created_at timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending', 'approved', 'featured')),
  likes_count integer not null default 0,
  instagram_handle text
);

create table if not exists bia_subscription_profiles (
  email text primary key,
  user_id text,
  status text not null default 'pending' check (status in ('pending', 'active', 'expired', 'trial')),
  subscription_expires_at timestamptz,
  last_payment_id text,
  updated_at timestamptz not null default now()
);

alter table bia_subscription_profiles add column if not exists user_id text;

create table if not exists bia_payment_intents (
  payment_id text primary key,
  user_id text,
  email text not null,
  amount_cents integer not null check (amount_cents > 0),
  status text not null default 'pending' check (status in ('pending', 'active')),
  provider_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists bia_shared_content (
  content_key text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists bia_student_progress (
  user_id text primary key,
  sessions jsonb not null default '[]'::jsonb,
  glossary jsonb not null default '{}'::jsonb,
  learned_words jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists bia_ceo_friend_messages (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  receiver_id text not null,
  body text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '5 days')
);

-- Centralized trial coupons: shared across every device/browser so a code can
-- only ever be redeemed once, closing the local-storage-only reuse loophole.
create table if not exists bia_trial_coupons (
  id text primary key,
  code text not null unique,
  days integer not null default 5,
  is_used boolean not null default false,
  used_by_email text,
  used_at timestamptz,
  expires_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

insert into bia_trial_coupons (id, code, days, is_used, notes)
values
  ('coupon_default_1', 'BIA-5DIAS', 5, false, 'Cupom Padrão de 5 Dias Grátis'),
  ('coupon_default_2', 'DEGUSTA5', 5, false, 'Degustação 5 Dias de Acesso'),
  ('coupon_default_3', 'BRAZILIAN5', 5, false, 'Cupom Promocional Brazilian 5 Dias')
on conflict (code) do nothing;

create index if not exists idx_shared_content_updated_at on bia_shared_content (updated_at desc);
create index if not exists idx_student_progress_updated_at on bia_student_progress (updated_at desc);
create index if not exists idx_friend_messages_expires_at on bia_ceo_friend_messages (expires_at);
create index if not exists idx_trial_coupons_code on bia_trial_coupons (code);
create index if not exists idx_payment_intents_email on bia_payment_intents (email);

create index if not exists idx_profiles_email on profiles (email);
create unique index if not exists idx_profiles_auth_user_id on profiles (auth_user_id) where auth_user_id is not null;
create index if not exists idx_stories_created_at on stories (created_at desc);
create index if not exists idx_stories_status on stories (status);
create index if not exists idx_subscription_email on bia_subscription_profiles (email);

alter table profiles enable row level security;
alter table stories enable row level security;
alter table bia_subscription_profiles enable row level security;
alter table bia_shared_content enable row level security;
alter table bia_student_progress enable row level security;
alter table bia_ceo_friend_messages enable row level security;
alter table bia_trial_coupons enable row level security;
alter table bia_payment_intents enable row level security;

drop policy if exists "profiles_all_access" on profiles;
drop policy if exists "profiles_select_own" on profiles;
create policy "profiles_select_own" on profiles
for select to authenticated using (auth_user_id = auth.uid()::text);

drop policy if exists "stories_all_access" on stories;
drop policy if exists "stories_public_read_approved" on stories;
create policy "stories_public_read_approved" on stories
for select to anon, authenticated using (status in ('approved', 'featured'));
drop policy if exists "stories_insert_own_pending" on stories;
create policy "stories_insert_own_pending" on stories
for insert to authenticated with check (student_id = auth.uid()::text and status = 'pending');
drop policy if exists "stories_update_own_pending" on stories;
create policy "stories_update_own_pending" on stories
for update to authenticated using (student_id = auth.uid()::text and status = 'pending')
with check (student_id = auth.uid()::text and status = 'pending');
drop policy if exists "stories_delete_own_pending" on stories;
create policy "stories_delete_own_pending" on stories
for delete to authenticated using (student_id = auth.uid()::text and status = 'pending');

drop policy if exists "subscription_all_access" on bia_subscription_profiles;
drop policy if exists "Read subscription status" on bia_subscription_profiles;
drop policy if exists "subscription_select_own" on bia_subscription_profiles;
create policy "subscription_select_own" on bia_subscription_profiles
for select to authenticated using (user_id = auth.uid()::text);

drop policy if exists "shared_content_all_access" on bia_shared_content;
drop policy if exists "shared_content_public_read" on bia_shared_content;

drop policy if exists "student_progress_all_access" on bia_student_progress;
drop policy if exists "student_progress_own" on bia_student_progress;
create policy "student_progress_own" on bia_student_progress
for all to authenticated using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);

drop policy if exists "ceo_friend_messages_all_access" on bia_ceo_friend_messages;
drop policy if exists "ceo_friend_messages_participant_read" on bia_ceo_friend_messages;
create policy "ceo_friend_messages_participant_read" on bia_ceo_friend_messages
for select to authenticated using (sender_id = auth.uid()::text or receiver_id = auth.uid()::text);
drop policy if exists "ceo_friend_messages_sender_insert" on bia_ceo_friend_messages;
create policy "ceo_friend_messages_sender_insert" on bia_ceo_friend_messages
for insert to authenticated with check (sender_id = auth.uid()::text);
drop policy if exists "ceo_friend_messages_sender_delete" on bia_ceo_friend_messages;
create policy "ceo_friend_messages_sender_delete" on bia_ceo_friend_messages
for delete to authenticated using (sender_id = auth.uid()::text);

drop policy if exists "trial_coupons_all_access" on bia_trial_coupons;
drop policy if exists "trial_coupons_public_read" on bia_trial_coupons;
create policy "trial_coupons_public_read" on bia_trial_coupons
for select using (false);

drop policy if exists "payment_intents_select_own" on bia_payment_intents;
create policy "payment_intents_select_own" on bia_payment_intents
for select to authenticated using (user_id = auth.uid()::text);

revoke all on public.profiles, public.bia_subscription_profiles, public.bia_trial_coupons from anon, authenticated;
grant select on public.profiles, public.bia_subscription_profiles to authenticated;
revoke all on public.bia_payment_intents from anon, authenticated;
grant select on public.bia_payment_intents to authenticated;
grant all on public.bia_payment_intents to service_role;
grant select on public.bia_trial_coupons to anon, authenticated;
revoke all on public.stories from anon, authenticated;
grant select on public.stories to anon, authenticated;
grant insert, update, delete on public.stories to authenticated;
revoke all on public.bia_shared_content from anon, authenticated;
revoke all on public.bia_student_progress, public.bia_ceo_friend_messages from anon, authenticated;
grant select, insert, update, delete on public.bia_student_progress, public.bia_ceo_friend_messages to authenticated;

revoke select, insert, update, delete on table bia_trial_coupons from anon, authenticated;

create or replace function check_trial_coupon(requested_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare found_coupon bia_trial_coupons;
begin
  select * into found_coupon
  from bia_trial_coupons
  where upper(code) = upper(trim(requested_code))
    and is_used = false
    and (expires_at is null or expires_at > now())
  limit 1;

  if found_coupon.id is null then
    return jsonb_build_object('ok', false);
  end if;

  return jsonb_build_object(
    'ok', true,
    'coupon', jsonb_build_object('code', found_coupon.code, 'days', found_coupon.days)
  );
end;
$$;

revoke all on function check_trial_coupon(text) from public;
grant execute on function check_trial_coupon(text) to anon, authenticated;

create or replace function redeem_trial_coupon(requested_code text, redeemer_email text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  redeemed_coupon bia_trial_coupons;
begin
  update bia_trial_coupons
  set is_used = true,
      used_by_email = lower(trim(redeemer_email)),
      used_at = now()
  where upper(code) = upper(trim(requested_code))
    and is_used = false
    and (expires_at is null or expires_at > now())
  returning * into redeemed_coupon;

  if redeemed_coupon.id is null then
    return jsonb_build_object('ok', false, 'reason', 'invalid_or_used');
  end if;

  return jsonb_build_object(
    'ok', true,
    'coupon', jsonb_build_object('code', redeemed_coupon.code, 'days', redeemed_coupon.days)
  );
end;
$$;

revoke all on function redeem_trial_coupon(text, text) from public;
grant execute on function redeem_trial_coupon(text, text) to anon, authenticated;

create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists profiles_updated_at on profiles;
create trigger profiles_updated_at
before update on profiles
for each row
execute function update_updated_at_column();

drop trigger if exists subscriptions_updated_at on bia_subscription_profiles;
create trigger subscriptions_updated_at
before update on bia_subscription_profiles
for each row
execute function update_updated_at_column();

drop trigger if exists shared_content_updated_at on bia_shared_content;
create trigger shared_content_updated_at
before update on bia_shared_content
for each row execute function update_updated_at_column();

drop trigger if exists student_progress_updated_at on bia_student_progress;
create trigger student_progress_updated_at
before update on bia_student_progress
for each row execute function update_updated_at_column();

create or replace function purge_expired_friend_messages()
returns trigger as $$
begin
  delete from bia_ceo_friend_messages where expires_at <= now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists purge_friend_messages_before_insert on bia_ceo_friend_messages;
create trigger purge_friend_messages_before_insert
before insert on bia_ceo_friend_messages
for each row execute function purge_expired_friend_messages();
